### ISSUE TITLE
OpenComputers robot

### ISSUE THREAD

**Issue by shortybsd** [PEXPlugins/Modifyworld#105]
I've noticed with Modifyworld disabled my OpenComputer robots can break/place and attack. When Modifyworld is enabled they are denied but nothing is in the logs. I have trusted all the robot permissions and when enabling pex debug toggle I never see any permissions getting hit from the robot when it tries one of those 3 actions. Is there a way I can see a log of what is getting blocked exactly or do you know of something I can do to bypass it? On the robot I just get false for the function to break/place or attack. Since I cannot see a msg with getting a denied error from Modifyworld on the robot itself is there a way to look at a particular log to find this info? I haven't found anything in my logs stating denied for these. Thanks.

**Comment by Cronosus** [comment]
have same problem

**Comment by shortybsd** [comment]
lol 3 years later? I no longer run Pex so no longer an issue. ThutPerms for Forge is the way to go.

**Comment by zml2008** [comment]
Conveniently enough both PEX and modifyWorld are discontinued so this works out fine for most of us
________________________________
