### ISSUE TITLE
Players cant chat even when the node is applied

### ISSUE THREAD

**Issue by marioandluigi878** [PEXPlugins/Modifyworld#107]
so like the title says for some reason players cant talk unless they are oped or the plugin is completely removed 

groups:
  Civilian:
    options:
      default: true
      prefix: '&0[Civilian] &d'
    permissions:
    - modifyworld.blocks.interact.*
    - modifyworld.*
    - modifyworld.blocks.place.*
    - modifyworld.chat
    - plotme.use.claim
    - plotme.use.auto
    - plotme.use.home
    - plotme.use.clear
    - plotme.use.dispose
    - plotme.use.deny
    - plotme.use.undeny
    - plotme.use.add
    - plotme.use.remove
    - plotme.limit.1
    - essentials.kits.Tools
    - essentials.kits.Dtools
    - essentials.kits.Heads
    - essentials.kit
    - essentials.pay
    - essentials.sell
    - essentials.afk
    - essentials.afk.auto
    - essentials.help
    - essentials.ignore
    - essentials.info
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.motd
    - essentials.msg
    - essentials.rules
    - essentials.sethome
    - essentials.sethome.bed
    - essentials.tpa
    - essentials.tpahere
    - multiverse.access.self.plotworld
    - multiverse.access.self.world
    - multiverse.teleport.*

**Comment by marioandluigi878** [comment]
thanks for helping in advance

**Comment by marioandluigi878** [comment]
got it to work

**Comment by CatMe0w** [comment]
how did you do?
