### ISSUE TITLE
modifyworld 1.8

### ISSUE THREAD

**Issue by chillerkraft** [PEXPlugins/Modifyworld#109]
why isn't there an updated modifyworld? awaiting approval? ;P
i really like modifyworld but, i don't like to use it anymore because it seems like a bad idea,
i don't know if it's gonna mess with my server and i'm wanting to see an update, because it's past due for one. any info would be nice ty

**Comment by TheCookieNation** [comment]
I think the plugin is discontinued

**Comment by zml2008** [comment]
For modifyworld the version numbers don't mean anything -- you should be fine using the existing version. There isn't really much that needs to be updated.

**Comment by chillerkraft** [comment]
reallly!? that would be amazing!
i guess i'll go test modifyworld.damage.take.endermite, etc? maybe it automatically adds new mobs name, is that what your saying?

but modifyworld.items.put.<itemid>.of.<container> still doesn't work.... i know that for sure... UNLESS, something else is overriding that ability and allowing it to happen?

i suppose i'll try a test server for that with only permissionsex and modifyworld (:

**Comment by chillerkraft** [comment]
ho ly crap
the new mobs work with the "old" version!

EXTRA EXTRA READ ALL ABOUT THIS
