### ISSUE TITLE
-modifyworld.mobtarget.* not working

### ISSUE THREAD

**Issue by xdismembrdfreakx** [PEXPlugins/Modifyworld#126]
im trying to start a server solo and have been trying to get it so that mobs do not target me. ive used the   -modifyworld.mobtarget.* node before the '*' node in the owner group for perms. however it does not work no matter what ive tried! this is really frustrating as im trying to build this server from scratch so that i learn as i go. ive spent 2 days now trying to figure this one out. any help would be amazing. thanks.

edit: also note all these commands were from the console. and here is the pastebin: https://pastebin.com/RJNq9JJ6

**Comment by zml2008** [comment]
Either start maintaining MW yourself and fixing issues you find (MW is quite a nice plugin and I don't think its features have been replicated in anything else on Bukkit), or start using a plugin that hasn't been abandoned for years.
