### ISSUE TITLE
mod based entities ignore modifyworld.mobtarget but not modifyworld.damage.*

### ISSUE THREAD

**Issue by plaguewolf** [PEXPlugins/Modifyworld#98]
specificly my server has lycanites and they dont behave with worldgaurd either. pex toggle debug shows entity as lycanitesmobs[entityname] but on adding permission node                                             -modifyworld.mobtarget.lycanitesmobsgrue (grue mob from mod) the grue still targets players

tested it with -modifyworld.damage.take.lycanitesmobsgrue and that node works fine

**Comment by plaguewolf** [comment]
nothing? i realize that modifyworld is kinda outadeted. wasnt aware it was abandoned though. further testing reveals that tis not only lycanites mobs but in fact any entity added by a forge mod. can i have more info on how the modifyworld plugin interacts ith entity targeting hooks?

**Comment by zml2008** [comment]
probably the mod doesn't call Bukkit events correctly. Nothing we can do about a broken mod.
